---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: pgwatch2-deployment
    labels:
      app: pgwatch2
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: pgwatch2
    template:
      metadata:
        labels:
          app: pgwatch2
      spec:
        containers:
          - name: pgwatch2
            image: cybertec/pgwatch2-postgres:latest
            ports:
              - containerPort: 8080
              - containerPort: 8081
              - containerPort: 5432
              - containerPort: 3000
            volumeMounts:
              - mountPath: /pgwatch2/persistent-config
                name: pgwatch2-config
              - mountPath: /var/lib/postgresql
                name: pgwatch2-postgresql
              - mountPath: /var/lib/grafana
                name: pgwatch2-grafana
            livenessProbe:
              exec:
                command:
                  - /usr/bin/pg_isready
                  - -qU
                  - pgwatch2
              initialDelaySeconds: 30
              periodSeconds: 30
        volumes:
          - name: pgwatch2-config
            persistentVolumeClaim:
              claimName: pgwatch2-config
          - name: pgwatch2-postgresql
            persistentVolumeClaim:
              claimName: pgwatch2-postgresql
          - name: pgwatch2-grafana
            persistentVolumeClaim:
              claimName: pgwatch2-grafana
---
  kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: pgwatch2-config
    labels:
      app: pgwatch2
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
---
  kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: pgwatch2-postgresql
    labels:
      app: pgwatch2
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
---
  kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: pgwatch2-grafana
    labels:
      app: pgwatch2
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
#---
#  kind: Service
#  apiVersion: v1
#  metadata:
#    name: pgwatch2-webui
#  spec:
#    type: NodePort
#    selector:
#      app: pgwatch2
#    ports:
#      - port: 8080
#        protocol: TCP
#        targetPort: 8080
#---
#  kind: Service
#  apiVersion: v1
#  metadata:
#    name: pgwatch2-grafana
#  spec:
#    type: NodePort
#    selector:
#      app: pgwatch2
#    ports:
#      - port: 3000
#        protocol: TCP
#        targetPort: 3000
