---

- name: basic
  description: only the most important metrics - load, WAL, DB-level statistics (size, tx and backend counts)
  metrics:
    cpu_load: 60
    db_stats: 60
    wal: 60

- name: exhaustive
  description: all important metrics for a deeper performance understanding
  metrics:
    backends: 60
    bgwriter: 60
    change_events: 300
    cpu_load: 60
    db_stats: 60
    index_stats: 120
    locks: 60
    locks_mode: 60
    replication: 120
    replication_slots: 120
    sproc_stats: 60
    stat_statements: 120
    stat_statements_calls: 60
    table_bloat_approx_summary: 7200
    table_io_stats: 120
    table_stats: 120
    wal: 60

- name: minimal
  description: single "Key Performance Indicators" query for fast cluster/db overview
  metrics:
    kpi: 60

- name: pgbouncer
  description: per DB stats
  metrics:
    pgbouncer_stats: 60

- name: standard
  description: basic level + table, index, stat_statements stats
  metrics:
    cpu_load: 60
    db_stats: 60
    index_stats: 120
    sproc_stats: 120
    stat_statements: 120
    table_stats: 120
    wal: 60

- name: full
  description: almost all available metrics for a even deeper performance understanding
  metrics:
    backends: 60
    bgwriter: 60
    change_events: 300
    cpu_load: 60
    db_stats: 60
    index_stats: 120
    locks: 60
    locks_mode: 60
    replication: 120
    replication_slots: 120
    sproc_stats: 60
    stat_statements: 120
    stat_statements_calls: 60
    table_bloat_approx_summary: 7200
    table_io_stats: 120
    table_stats: 120
    wal: 60
    kpi: 120
    pg_stat_ssl: 120
    psutil_cpu: 120
    psutil_mem: 120
    psutil_disk: 120
    psutil_disk_io_total: 120

- name: unprivileged
  description: no wrappers + only pg_stat_statements extension expected (developer mode)
  metrics:
    bgwriter: 60
    change_events: 300
    db_stats: 60
    index_stats: 120
    locks: 60
    locks_mode: 60
    replication: 120
    replication_slots: 120
    sproc_stats: 60
    stat_statements_calls: 60
    table_io_stats: 120
    table_stats: 120
    wal: 60
