---

- name: basic
  description: only the most important metrics - WAL, DB-level statistics (size, tx and backend counts)
  metrics:
    db_stats: 60
    db_size: 300
    wal: 60

- name: exhaustive
  description: all important metrics for a deeper performance understanding
  metrics:
    archiver: 60
    backends: 60
    bgwriter: 60
    checkpointer: 60
    change_events: 300
    cpu_load: 60
    db_stats: 60
    db_size: 300
    index_stats: 900
    locks: 60
    locks_mode: 60
    replication: 120
    replication_slots: 120
    settings: 7200
    sequence_health: 3600
    sproc_stats: 180
    stat_activity: 30
    stat_statements: 180
    stat_statements_calls: 60
    table_bloat_approx_summary_sql: 7200
    table_io_stats: 600
    table_stats: 300
    wal: 60
    wal_size: 300
    wal_receiver: 120

- name: minimal
  description: single "Key Performance Indicators" query for fast cluster/db overview
  metrics:
    kpi: 60

- name: pgbouncer
  description: per DB stats
  metrics:
    pgbouncer_stats: 60

- name: pgpool
  description: pool global stats, 1 row per node ID
  metrics:
    pgpool_stats: 60

- name: standard
  description: basic level + table, index, stat_statements stats
  metrics:
    cpu_load: 60
    db_stats: 60
    db_size: 300
    index_stats: 900
    sequence_health: 3600
    sproc_stats: 180
    stat_statements: 180
    table_stats: 300
    wal: 60

- name: full
  description: almost all available metrics for a even deeper performance understanding
  metrics:
    archiver: 60
    backends: 60
    bgwriter: 60
    checkpointer: 60
    change_events: 300
    cpu_load: 60
    db_stats: 60
    db_size: 300
    index_stats: 900
    instance_up: 60
    locks: 60
    locks_mode: 60
    recommendations: 43200
    replication: 120
    replication_slots: 120
    logical_subscriptions: 120
    server_log_event_counts: 60
    settings: 7200
    sequence_health: 3600
    sproc_stats: 180
    stat_activity: 30
    stat_statements: 180
    stat_statements_calls: 60
    table_bloat_approx_summary_sql: 7200
    table_io_stats: 600
    table_stats: 300
    wal: 60
    wal_size: 120
    kpi: 120
    stat_ssl: 120
    psutil_cpu: 120
    psutil_mem: 120
    psutil_disk: 120
    psutil_disk_io_total: 120
    wal_receiver: 120

# the Docker image with Influx metric storage cannot handle more recommendations...
- name: full_influx
  description: almost all available metrics for a even deeper performance understanding
  metrics:
    archiver: 60
    backends: 60
    bgwriter: 60
    checkpointer: 60
    change_events: 300
    cpu_load: 60
    db_stats: 60
    db_size: 300
    index_stats: 900
    locks: 60
    locks_mode: 60
    recommendations: 43200
    replication: 120
    replication_slots: 120
    logical_subscriptions: 120
    server_log_event_counts: 60
    settings: 7200
    sequence_health: 3600
    sproc_stats: 180
    stat_statements: 180
    stat_statements_calls: 60
    table_bloat_approx_summary_sql: 7200
    table_io_stats: 600
    table_stats: 300
    wal: 60
    wal_size: 120
    kpi: 120
    stat_ssl: 120
    psutil_cpu: 120
    psutil_mem: 120
    psutil_disk: 120
    psutil_disk_io_total: 120
    wal_receiver: 120

- name: unprivileged
  description: no wrappers + only pg_stat_statements extension expected (developer mode)
  metrics:
    archiver: 60
    bgwriter: 60
    checkpointer: 60
    change_events: 300
    db_stats: 60
    db_size: 300
    index_stats: 900
    locks: 60
    locks_mode: 60
    replication: 120
    replication_slots: 120
    settings: 7200
    sequence_health: 3600
    sproc_stats: 180
    stat_statements_calls: 60
    table_io_stats: 600
    table_stats: 300
    wal: 60

- name: prometheus
  description: similar to "exhaustive" but without some possibly longer-running metrics and those keeping state
  metrics:
    archiver: 1
    backends: 1
    bgwriter: 1
    cpu_load: 1
    db_stats: 1
    db_size: 1
    locks_mode: 1
    replication: 1
    replication_slots: 1
    sproc_stats: 1
    stat_statements_calls: 1
    table_stats: 1
    wal: 1
    wal_receiver: 1

- name: prometheus-async
  description: tuned for the new async (background collection) Prom feature. NB! Prom tolerates max. 10min time lag, so intervals should be smaller than 600
  metrics:
    backends: 30
    bgwriter: 60
    checkpointer: 60
    db_stats: 30
    db_size: 300
    locks_mode: 30
    replication: 120
    replication_slots: 120
    settings: 300
    sproc_stats: 180
    stat_statements_calls: 60
    table_io_stats: 300
    table_stats: 300
    wal: 60
    wait_events: 60

- name: superuser_no_python
  description: like exhaustive, but no PL/Python helpers
  metrics:
    archiver: 60
    backends: 60
    bgwriter: 60
    checkpointer: 60
    change_events: 300
    db_stats: 60
    db_size: 300
    index_stats: 900
    locks: 60
    locks_mode: 60
    replication: 120
    replication_slots: 120
    settings: 7200
    sequence_health: 3600
    sproc_stats: 180
    stat_activity: 30
    stat_statements: 180
    stat_statements_calls: 60
    table_bloat_approx_summary_sql: 7200
    table_io_stats: 600
    table_stats: 300
    wal: 60
    wal_size: 300
    wal_receiver: 120

- name: aurora
  description: AWS Aurora doesn't expose all Postgres functions and there's no WAL
  metrics:
    archiver: 60
    backends: 60
    bgwriter: 60
    checkpointer: 60
    change_events: 300
    db_stats_aurora: 60
    db_size: 300
    index_stats: 900
    locks: 60
    locks_mode: 60
    replication: 120
    replication_slots: 120
    settings: 7200
    sproc_stats: 180
    stat_statements: 180
    stat_statements_calls: 60
    table_bloat_approx_summary_sql: 7200
    table_io_stats: 600
    table_stats: 300
    wal_receiver: 120

- name: aiven
  description: aiven database metrics
  metrics:
    archiver: 60
    backends: 60
    bgwriter: 60
    checkpointer: 60
    change_events: 300
    db_stats: 60
    db_size: 300
    index_col_stats: 86400
    index_stats: 900
    locks: 60
    locks_mode: 60
    recommendations: 43200
    replication: 120
    replication_slots: 120
    settings: 7200
    sequence_health: 3600
    sproc_stats: 180
    stat_activity: 60
    stat_statements: 180
    stat_statements_calls: 60
    table_bloat_approx_summary_sql: 7200
    table_io_stats: 300
    table_stats: 300
    wal: 60
    wal_receiver: 120

- name: rds
  description: similar to 'exhaustive' with stuff that's not accessible on AWS RDS removed
  metrics:
    archiver: 60
    backends: 60
    bgwriter: 60
    checkpointer: 60
    change_events: 300
    db_stats: 60
    db_size: 300
    index_stats: 900
    locks: 60
    locks_mode: 60
    replication: 120
    replication_slots: 120
    settings: 7200
    sequence_health: 3600
    sproc_stats: 180
    stat_activity: 30
    stat_statements: 180
    stat_statements_calls: 60
    table_bloat_approx_summary_sql: 7200
    table_io_stats: 600
    table_stats: 300
    wal: 60
    wal_receiver: 120

- name: azure
  description: similar to 'exhaustive' with stuff that's not accessible on Azure Database for PostgreSQL removed
  metrics:
    kpi: 120
    wal: 60
    wal_size: 300
    locks: 60
    db_size: 300
    archiver: 60
    backends: 60
    bgwriter: 60
    checkpointer: 60
    db_stats: 60
    settings: 7200
    stat_ssl: 60
    locks_mode: 60
    index_stats: 900
    replication: 60
    sproc_stats: 180
    wal_receiver: 60
    change_events: 300
    table_io_stats: 600
    stat_statements: 180
    sequence_health: 3600
    replication_slots: 60
    stat_statements_calls: 60
    table_bloat_approx_summary_sql: 7200

- name: gce
  description: similar to 'exhaustive' with stuff not accessible on GCE managed PostgreSQL engine removed
  metrics:
    archiver: 60
    backends: 60
    bgwriter: 60
    checkpointer: 60
    change_events: 300
    db_stats: 60
    db_size: 300
    index_stats: 900
    locks: 60
    locks_mode: 60
    replication: 120
    replication_slots: 120
    settings: 7200
    sequence_health: 3600
    sproc_stats: 180
    stat_statements: 180
    stat_statements_calls: 60
    table_bloat_approx_summary_sql: 7200
    table_io_stats: 600
    table_stats: 300
    wal: 60
    wal_receiver: 120

- name: remotedba
  description: Metrics used for monitoring of Remote-DBA Databases
  metrics:
    kpi: 120
    wal: 60
    locks: 60
    db_size: 300
    archiver: 60
    backends: 60
    bgwriter: 60
    checkpointer: 60
    cpu_load: 60
    db_stats: 60
    settings: 7200
    wal_size: 300
    locks_mode: 60
    index_stats: 900
    replication: 120
    sproc_stats: 180
    table_stats: 300
    wal_receiver: 120
    change_events: 300
    table_io_stats: 600
    sequence_health: 3600
    replication_slots: 120
    psutil_cpu: 120
    psutil_mem: 120
    psutil_disk: 120
