name: Build & Test
on:
  pull_request:
  workflow_dispatch:

jobs:

  test-docker-images:
    if: ${{ github.event.pull_request.head.repo.full_name == 'cybertec-postgresql/pgwatch2' }} # allow only local repo PRs
    name: Test Docker Image on Ubuntu
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Version strings
      id: version
      run: |
        echo "PR_VERSION=$(echo "$GITHUB_REF_NAME#${GITHUB_SHA:0:6}")" >> $GITHUB_OUTPUT
        echo "PR_TIME=$(git show -s --format=%cI HEAD)" >> $GITHUB_OUTPUT
        echo "PR_TAGNAME"=$(echo $GITHUB_REF_NAME | tr // _) >> $GITHUB_OUTPUT

    - name: Publish test version to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      env:
        GIT_HASH: ${{ steps.version.outputs.PR_VERSION }}
        GIT_TIME: ${{ steps.version.outputs.PR_TIME }}
        TAG_NAME: ${{ steps.version.outputs.PR_TAGNAME }}
      with:
        name: cybertec/pgwatch2-postgres
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/Dockerfile-postgres
        buildargs: GIT_HASH,GIT_TIME
        tags: ${{ steps.version.outputs.PR_TAGNAME }}